name: Update all-time commits badge

on:
  # you can adjust the schedule as you like:
  schedule:
    - cron: '0 0 * * *'     # daily at midnight UTC
  workflow_dispatch:       # manual trigger

jobs:
  update-commit-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Fetch all-time commit count
        run: |
          node .github/scripts/fetch-commit-count.js \
            --user "$GITHUB_REPOSITORY_OWNER" \
            --out-file commit-count.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push updated badge
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update all-time commit count badge"
          file_pattern: commit-count.json
          branch: main
