name: Update all-time commits badge

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-commit-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Fetch all-time commit count
        run: node .github/scripts/fetch-commit-count.js \
               --out-file commit-count.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

      - name: Commit and push updated badge
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update all-time commit count badge"
          file_pattern: commit-count.json
          branch: main
